### ISSUE TITLE
Not possible to open a hyperion.config.json file

### ISSUE THREAD

**Issue by cmvac** [tvdzwan/hypercon#10]
Hi Tvdzwan,

Is there anyway to open a already made hyperion.config.json file with Hypercon? I had to reinstall my laptop and lost all configurations I had for my Ambilight system. I have my already tweaked Hyperion file, but I'd like to edit it with Hypercon instead of doing it manually. I need to adjust the image process configurations, which manually are a pain in the A to do.

It would be excellent if there was an "open file" option on Hypercon!

**Comment by soeren-helbig** [comment]
+1

**Comment by Paulchen-Panther** [comment]
+1

**Comment by brindosch** [comment]
Maybe you could use the Hypercon_SSH.jar
it generates automatically a hypercon.dat
If you save this .dat at a save place (maybe a hyperion "project" folder)
you never lost your configuration

**Comment by brindosch** [comment]
A new HyperCon will arive soon. Now you could load and save a "HyperCon_settings.dat". Just store/backup this file!

I added your wish to the wishlist

Closed

**Comment by danielandross** [comment]
+1
I want to download a configured json file from somebody who uses the same led strip and only change the led count.
