### ISSUE TITLE
Inst./Upd not outputting correct led amount. 

### ISSUE THREAD

**Issue by simonwicks** [tvdzwan/hypercon#13]
I'm using Raspberry Pi 3, and OpenELEC v6.0.3 from the lightberry site. 

When I use the Inst./Upd button under ssh, it only puts 45 leds in the config file. 
If I use the create hyperion config button, I get all my leds, 106 in my case. 

I thought this might be why only half my leds were working, but even replacing the ssh version with the manual version it's still not working. But one problem at a time. 

Loving this new release though, the ssh option makes it so much easier to test things. 

Although, the ssh commands box doesn't work on my install of openelec. Not sure if that's the same for all versions, and if there's another way of stopping / restarting without having to reboot. 

`ssh out: 	sudo service hyperion restart
ssh in: 	 There is no working 'sudo'.
ssh in: 	 
ssh in: 	 On debian/ubuntu/all general purpose linux distributions 'sudo'
ssh in: 	 allows a permitted user to execute a command as the superuser
ssh in: 	 or another user, as specified by the security policy
ssh in: 	 
ssh in: 	 With OpenELEC you have root access by default, so you dont need 'sudo'`

**Comment by brindosch** [comment]
On top of the ssh tap you have to choose your distribution (OpenELEC)
The inst/Update button is just to update your Hyperion. It won´t replace/change your config.
I will work on a config file upload - later.

Thank you for feedback

**Comment by simonwicks** [comment]
I have chosen OpenELEC as the distro, it connects fine and can uninstall / install. But the commands to restart etc don't work. I've realised I can actually type what I want in there too, but I'm not really all that sure what I'm doing with commands, so I don't know what to manually put in instead. Not sure if it's a problem with the lightberry build I'm using though.

I didn't realise the buttons were only for first time install/update though, and not updating the config itself, so thanks for clearing that up!

**Comment by brindosch** [comment]
the problem is, you need to know what to type in and OpenELEC is a sepcial case.
In future i´m planing to remove that field and add start/stop/status/get log -buttons instead.
--> Should be much easier and faster

**Comment by brindosch** [comment]
@simonwicks 
Config upload is now added.
Have fun
