### ISSUE TITLE
Hypercon OK but HyperCon_ssh bugged.

### ISSUE THREAD

**Issue by Alomamabobo** [tvdzwan/hypercon#7]
Hello,
HyperCon_ssh.jar output file is "Baudrate" where it have to be "rate". Doesnt happen with HyperCon.jar.
My 2 cents ;)

**Comment by tvdzwan** [comment]
Thanks. Hypercon.jar is a few releases behind because there are some issues with how the SSH code was added. The HyperCon_ssh.jar is the latest release. I fixed the issue, it should output the correct values now.

**Comment by cmvac** [comment]
Hi Tvdzwan, 

first off, thanks for your great software! I am trying to use hypercon_ssh.jar with Openelec (latest stable edition) but I always get:

ssh out: 	hyperion-remote  -c 89ff65
ssh error: 	sh: hyperion-remote: not found

Is this newest version of Hypercon not yet working with Openelec?

**Comment by brindosch** [comment]
@cmvac 
Try the latest release, choose Openelec als target system

I will close this
Thank you
