### ISSUE TITLE
Multi-Lightpack config output results in incorrect type

### ISSUE THREAD

**Issue by Sp0rks** [tvdzwan/hypercon#9]
when using HyperCon_ssh (multi-lightpack is not an option in HyperCon) to generate a multi-lightpack config it generates the type as multi_lightpack which is invalid and requires manual adjustment to multi-lightpack for it to work correctly

**Comment by brindosch** [comment]
@Sp0rks 
it still present, is on the todo

**Comment by brindosch** [comment]
@Sp0rks 
fixed in the latest version, thank you
/closed
